{{- $needSecret := or (and .Values.admin.password (not .Values.admin.existingSecret)) (and .Values.s3.enabled (or .Values.s3.accessKeyId .Values.s3.secretAccessKey) (not .Values.s3.existingSecret)) }}
{{- if $needSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-viewer.fullname" . }}
  labels:
    {{- include "log-viewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.admin.password (not .Values.admin.existingSecret) }}
  password: {{ .Values.admin.password | quote }}
  {{- end }}
  {{- if and .Values.s3.enabled (not .Values.s3.existingSecret) }}
  {{- if .Values.s3.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.s3.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  {{- end }}
  {{- end }}
{{- end }}
